# This file was generated by GoReleaser. DO NOT EDIT.
cask "remembery" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "ccd5c9c0b805cac80ea2aba3918129dcf43ab0ce18abd63cfd2f9a7f2e6fb764"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8ace30dc49cbb08b0fafb169474225eff580fe4d48120e3d5b125a9f131a68b4"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bcb29537089823c0e0bbf18a505ca13f15106daea8c1cdaebb360ba54af487e9"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6389ed7dd6c34f29c4ff247dbc20ef4dad28626f237231179894e85cc1879c7d"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "remembery"
  desc "A small TUI for memorizing strings"
  homepage "https://github.com/alankiri/remembery"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remembery"

  # No zap stanza required

end
