# This file was generated by GoReleaser. DO NOT EDIT.
cask "remembery" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a33dcf673bea5727968bfcaa909bd8ea2c9c25dc1af1d0bebc472385c15e7497"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bba573ecd15cce39cac174ef764d6524f6a5196702dab41c4b074d5628f8d135"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "075c12064801d008ea689308d41d319e0c0cc05d7ffcadd9cd7a59296ca97c11"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b3e97768a707e2ebb5fd3c7d192828438d137bc47deb9345de68e8e75929e4e8"
      url "https://github.com/AlanKiri/remembery/releases/download/v#{version}/remembery_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "remembery"
  desc "A small TUI for memorizing strings"
  homepage "https://github.com/alankiri/remembery"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remembery"

  # No zap stanza required

end
